### ISSUE TITLE
Unable to compress CSS

### ISSUE THREAD

**Issue by laurentmuller** [dg/ftp-deployment#107]
Version: 3.0.1

### Bug Description
The CSS  compression used with  the `Preprocessor` class returns always the code 503.

### Steps To Reproduce
The following simple CSS file cannot be compressed:
```css
/**! compression tag for ftp-deployment */

table {
    table-layout: fixed;
    width: 100%;
}
```
### Expected Behavior
With an online compressor the result is:
```css
table{table-layout:fixed;width:100%}
```
